frontend:
  image: frontend
  tag: latest
  port: 80

backend:
  image: backend
  tag: latest
  port: 8081
  env:
    DB_URL: jdbc:postgresql://postgres:5432/crawlerdb
    DB_USER: postgres
    DB_PASSWORD: toor

fastapi:
  image: fastapi
  tag: latest
  port: 8000

postgres:
  image: postgres
  tag: 15
  port: 5432
  user: postgres
  password: toor
  db: crawlerdb

ingress:
  enabled: true
  host: webcrawler.local
  frontend:
    path: /
    servicePort: 80
  backend:
    path: /api
    servicePort: 8081

