frontend:
  image: frontend
  tag: latest
  port: 80

backend:
  image: backend
  tag: latest
  port: 8081

fastapi:
  image: fastapi
  tag: latest
  port: 8000

postgres:
  image: postgres
  tag: 15
  port: 5432
  user: postgres
  password: toor
  db: crawlerdb
