apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          ports:
            - containerPort: {{ .Values.port }}
