apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi
spec:
  selector:
    app: {{ .Release.Name }}-fastapi
  ports:
    - protocol: TCP
      port: {{ .Values.fastapi.port }}
      targetPort: {{ .Values.fastapi.port }}
  type: ClusterIP
