apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-postgres
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          ports:
            - containerPort: {{ .Values.port }}
